import 'package:flutter/material.dart';
import 'dart:async';
import '../../../services/chat_service.dart';
import '../../../services/message_filter_service.dart';
import '../../../services/auth_service.dart';
import '../../theme/app_colors.dart';

class ChatDetailScreen extends StatefulWidget {
  final String conversationId;
  final String recipientName;
  final String recipientAvatar;
  final bool isDarkMode;
  final bool isAutoGenerated;

  const ChatDetailScreen({
    super.key,
    required this.conversationId,
    required this.recipientName,
    required this.recipientAvatar,
    this.isDarkMode = true,
    this.isAutoGenerated = false,
  });

  @override
  State<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

class _ChatDetailScreenState extends State<ChatDetailScreen> {
  late TextEditingController _messageController;
  late Future<List<Map<String, dynamic>>> _messagesFuture;
  late Future<List<Map<String, dynamic>>> _participantsFuture;
  late StreamSubscription _messagesStream;
  String? _warningMessage;
  bool _isLoading = false;
  final AuthService _authService = AuthService();

  @override
  void initState() {
    super.initState();
    _messageController = TextEditingController();
    _loadMessages();
    _loadParticipants();
    _subscribeToMessages();
  }

  void _loadMessages() {
    _messagesFuture = ChatService().getMessages(widget.conversationId);
  }

  void _loadParticipants() {
    _participantsFuture = ChatService().getConversationParticipants(
      widget.conversationId,
    );
  }

  void _subscribeToMessages() {
    _messagesStream = ChatService()
        .subscribeToMessages(widget.conversationId)
        .listen((_) {
          setState(() {
            _loadMessages();
          });
        });
  }

  Future<void> _sendMessage() async {
    if (_messageController.text.trim().isEmpty) return;

    final messageContent = _messageController.text.trim();
    final currentUser = _authService.currentUser;

    if (currentUser == null) return;

    setState(() => _isLoading = true);

    try {
      // Analyze message for off-platform transaction attempts
      final analysis = MessageFilterService.analyzeMessage(messageContent);

      // Show warning if suspicious
      if (analysis['is_suspicious']) {
        setState(() {
          _warningMessage = analysis['risk_level'] == 'high'
              ? '⚠️ This message may contain contact details. Keep payments within the app for security.'
              : 'ℹ️ Reminder: Keep all transactions within the app for protection.';
        });
      } else {
        setState(() => _warningMessage = null);
      }

      // Send message
      await ChatService().sendMessage(
        conversationId: widget.conversationId,
        senderId: currentUser.id,
        content: messageContent,
      );

      // Flag if necessary
      if (analysis['should_flag']) {
        final messageId = DateTime.now().millisecondsSinceEpoch.toString();
        await MessageFilterService.flagMessageForReview(
          messageId: messageId,
          conversationId: widget.conversationId,
          senderId: currentUser.id,
          flagReason:
              'Potential off-platform transaction attempt: ${analysis['found_keywords'].join(', ')}',
          messageContent: messageContent,
        );

        // Show flag notification
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                '📋 Message has been flagged for safety review. Keep transactions within the app.',
              ),
              duration: Duration(seconds: 3),
              backgroundColor: AppColors.warning,
            ),
          );
        }
      }

      _messageController.clear();
      _loadMessages();
      _loadParticipants();

      if (mounted) {
        setState(() => _isLoading = false);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to send message: $e'),
            backgroundColor: AppColors.error,
          ),
        );
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  void dispose() {
    _messageController.dispose();
    _messagesStream.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = widget.isDarkMode;
    final bgColor = isDark ? AppColors.darkBg : AppColors.lightBg;
    final cardColor = isDark ? AppColors.darkCard : Colors.white;
    final textColor = isDark
        ? AppColors.textPrimary
        : AppColors.lightTextPrimary;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        backgroundColor: bgColor,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: textColor),
          onPressed: () => Navigator.pop(context),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                if (widget.isAutoGenerated)
                  Container(
                    margin: const EdgeInsets.only(right: 8),
                    padding: const EdgeInsets.symmetric(
                      horizontal: 6,
                      vertical: 2,
                    ),
                    decoration: BoxDecoration(
                      color: AppColors.success.withValues(alpha: 0.2),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: const Text(
                      '🤖 Auto',
                      style: TextStyle(
                        fontSize: 10,
                        color: AppColors.success,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                Text(
                  widget.recipientName,
                  style: TextStyle(
                    color: textColor,
                    fontWeight: FontWeight.w600,
                    fontSize: 16,
                  ),
                ),
              ],
            ),
            if (widget.isAutoGenerated)
              Text(
                'Conversation created automatically on booking confirmation',
                style: TextStyle(
                  fontSize: 11,
                  color: isDark
                      ? AppColors.textTertiary
                      : AppColors.lightTextTertiary,
                  fontWeight: FontWeight.w400,
                ),
              ),
          ],
        ),
      ),
      body: Column(
        children: [
          _buildParticipantReference(isDark, cardColor, textColor),

          // Messages list
          Expanded(
            child: FutureBuilder<List<Map<String, dynamic>>>(
              future: _messagesFuture,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Text(
                      'Error loading messages',
                      style: TextStyle(color: textColor),
                    ),
                  );
                }

                final messages = snapshot.data ?? [];

                if (messages.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        if (widget.isAutoGenerated)
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 24,
                              vertical: 16,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.success.withValues(alpha: 0.1),
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(
                                color: AppColors.success,
                                width: 1,
                              ),
                            ),
                            child: Column(
                              children: [
                                Icon(
                                  Icons.check_circle,
                                  color: AppColors.success,
                                  size: 32,
                                ),
                                const SizedBox(height: 8),
                                Text(
                                  'Conversation Started',
                                  style: TextStyle(
                                    fontSize: 14,
                                    fontWeight: FontWeight.w600,
                                    color: textColor,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  'This conversation was automatically created when the booking was confirmed. Start messaging now!',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: isDark
                                        ? AppColors.textSecondary
                                        : AppColors.lightTextSecondary,
                                  ),
                                ),
                              ],
                            ),
                          )
                        else
                          Icon(
                            Icons.chat_bubble_outline,
                            size: 48,
                            color: isDark
                                ? AppColors.textTertiary
                                : AppColors.lightTextTertiary,
                          ),
                        const SizedBox(height: 12),
                        Text(
                          'No messages yet',
                          style: TextStyle(color: textColor),
                        ),
                      ],
                    ),
                  );
                }

                return ListView.builder(
                  reverse: true,
                  padding: const EdgeInsets.all(16),
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    final message = messages[index];
                    final isAutoGenerated =
                        message['is_auto_generated'] == true;
                    final currentUserId = _authService.currentUser?.id;
                    final isCurrentUser = message['sender_id'] == currentUserId;

                    return Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Column(
                        crossAxisAlignment: isCurrentUser
                            ? CrossAxisAlignment.end
                            : CrossAxisAlignment.start,
                        children: [
                          // Auto-message badge
                          if (isAutoGenerated)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 4),
                              child: Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                decoration: BoxDecoration(
                                  color: AppColors.primary.withValues(
                                    alpha: 0.1,
                                  ),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: const Text(
                                  '🤖 Auto-generated message',
                                  style: TextStyle(
                                    fontSize: 10,
                                    color: AppColors.primary,
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                              ),
                            ),
                          // Message bubble
                          Container(
                            constraints: const BoxConstraints(maxWidth: 280),
                            padding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 8,
                            ),
                            decoration: BoxDecoration(
                              color: isCurrentUser
                                  ? AppColors.primary
                                  : (isDark
                                        ? AppColors.darkBgSecondary
                                        : Colors.grey[200]),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Text(
                              (message['content'] ?? message['message'] ?? '')
                                  .toString(),
                              style: TextStyle(
                                fontSize: 14,
                                color: isCurrentUser
                                    ? Colors.black
                                    : (isDark
                                          ? AppColors.textPrimary
                                          : Colors.black),
                              ),
                            ),
                          ),
                          // Timestamp
                          Padding(
                            padding: const EdgeInsets.only(top: 4),
                            child: Text(
                              _formatTime(message['created_at']),
                              style: TextStyle(
                                fontSize: 11,
                                color: isDark
                                    ? AppColors.textTertiary
                                    : AppColors.lightTextTertiary,
                              ),
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                );
              },
            ),
          ),

          // Warning message
          if (_warningMessage != null)
            Container(
              margin: const EdgeInsets.all(12),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppColors.warning.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppColors.warning),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.warning_outlined,
                    color: AppColors.warning,
                    size: 18,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      _warningMessage!,
                      style: const TextStyle(
                        fontSize: 12,
                        color: AppColors.warning,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ],
              ),
            ),

          // Message input
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: cardColor,
              border: Border(
                top: BorderSide(
                  color: isDark
                      ? AppColors.borderColor
                      : AppColors.lightBorderColor,
                ),
              ),
            ),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _messageController,
                    maxLines: 3,
                    minLines: 1,
                    enabled: !_isLoading,
                    decoration: InputDecoration(
                      hintText: 'Type your message...',
                      hintStyle: TextStyle(
                        color: isDark
                            ? AppColors.textTertiary
                            : AppColors.lightTextTertiary,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: BorderSide(
                          color: isDark
                              ? AppColors.borderColor
                              : AppColors.lightBorderColor,
                        ),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 8,
                      ),
                    ),
                    style: TextStyle(color: textColor),
                  ),
                ),
                const SizedBox(width: 8),
                Container(
                  decoration: BoxDecoration(
                    color: AppColors.primary,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: IconButton(
                    icon: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color>(
                                Colors.black,
                              ),
                            ),
                          )
                        : const Icon(Icons.send, color: Colors.black),
                    onPressed: _isLoading ? null : _sendMessage,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _formatTime(String? dateString) {
    if (dateString == null) return '';
    try {
      final date = DateTime.parse(dateString);
      final now = DateTime.now();
      final diff = now.difference(date);

      if (diff.inMinutes < 1) return 'now';
      if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
      if (diff.inHours < 24) return '${diff.inHours}h ago';
      if (diff.inDays < 7) return '${diff.inDays}d ago';

      return '${date.day}/${date.month}';
    } catch (e) {
      return '';
    }
  }

  Widget _buildParticipantReference(
    bool isDark,
    Color cardColor,
    Color textColor,
  ) {
    return FutureBuilder<List<Map<String, dynamic>>>(
      future: _participantsFuture,
      builder: (context, snapshot) {
        final participants = snapshot.data ?? [];

        if (snapshot.connectionState == ConnectionState.waiting) {
          return Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              color: cardColor,
              border: Border(
                bottom: BorderSide(
                  color: isDark
                      ? AppColors.borderColor
                      : AppColors.lightBorderColor,
                ),
              ),
            ),
            child: const SizedBox(
              height: 42,
              child: Align(
                alignment: Alignment.centerLeft,
                child: SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ),
            ),
          );
        }

        if (participants.isEmpty) {
          return const SizedBox.shrink();
        }

        return Container(
          width: double.infinity,
          padding: const EdgeInsets.fromLTRB(16, 10, 16, 12),
          decoration: BoxDecoration(
            color: cardColor,
            border: Border(
              bottom: BorderSide(
                color: isDark
                    ? AppColors.borderColor
                    : AppColors.lightBorderColor,
              ),
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Booking participants',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: isDark
                      ? AppColors.textSecondary
                      : AppColors.lightTextSecondary,
                ),
              ),
              const SizedBox(height: 8),
              SizedBox(
                height: 92,
                child: ListView.separated(
                  scrollDirection: Axis.horizontal,
                  itemCount: participants.length,
                  separatorBuilder: (_, _) => const SizedBox(width: 10),
                  itemBuilder: (context, index) {
                    return _buildParticipantCard(
                      participants[index],
                      isDark,
                      textColor,
                    );
                  },
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildParticipantCard(
    Map<String, dynamic> participant,
    bool isDark,
    Color textColor,
  ) {
    final name =
        participant['display_name']?.toString().trim().isNotEmpty == true
        ? participant['display_name'].toString().trim()
        : 'Unknown User';
    final role =
        participant['display_role']?.toString().trim().isNotEmpty == true
        ? participant['display_role'].toString().trim()
        : 'Participant';
    final email = participant['email']?.toString().trim() ?? '';
    final phone = participant['display_phone']?.toString().trim() ?? '';
    final avatar = participant['display_avatar']?.toString().trim() ?? '';
    final subtitle = phone.isNotEmpty
        ? phone
        : email.isNotEmpty
        ? email
        : 'No contact saved';

    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(10),
        onTap: () => _showParticipantDetails(participant, isDark, textColor),
        child: Ink(
          width: 230,
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: isDark
                ? AppColors.darkBgSecondary
                : AppColors.lightBgSecondary,
            borderRadius: BorderRadius.circular(10),
            border: Border.all(
              color: isDark
                  ? AppColors.borderColor
                  : AppColors.lightBorderColor,
            ),
          ),
          child: Row(
            children: [
              CircleAvatar(
                radius: 24,
                backgroundColor: AppColors.primary.withValues(alpha: 0.18),
                backgroundImage: avatar.isNotEmpty
                    ? NetworkImage(avatar)
                    : null,
                child: avatar.isEmpty
                    ? Text(
                        _initials(name),
                        style: const TextStyle(
                          color: AppColors.primary,
                          fontWeight: FontWeight.w800,
                        ),
                      )
                    : null,
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      role,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.w800,
                        color: AppColors.primary,
                      ),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w700,
                        color: textColor,
                      ),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      subtitle,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        fontSize: 11,
                        color: isDark
                            ? AppColors.textTertiary
                            : AppColors.lightTextTertiary,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(
                Icons.info_outline,
                size: 18,
                color: isDark
                    ? AppColors.textTertiary
                    : AppColors.lightTextTertiary,
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _showParticipantDetails(
    Map<String, dynamic> participant,
    bool isDark,
    Color textColor,
  ) {
    final name =
        participant['display_name']?.toString().trim().isNotEmpty == true
        ? participant['display_name'].toString().trim()
        : 'Unknown User';
    final role =
        participant['display_role']?.toString().trim().isNotEmpty == true
        ? participant['display_role'].toString().trim()
        : 'Participant';
    final avatar = participant['display_avatar']?.toString().trim() ?? '';
    final email = participant['email']?.toString().trim() ?? '';
    final phone = participant['display_phone']?.toString().trim() ?? '';
    final location = _firstValue(participant, [
      'location',
      'address',
      'city',
      'province',
    ]);
    final status = _firstValue(participant, [
      'status',
      'verification_status',
      'account_status',
    ]);
    final userId =
        participant['user_id']?.toString() ?? participant['id']?.toString();
    final joinedAt = _formatDateTime(participant['joined_at']?.toString());

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final sheetColor = isDark ? AppColors.darkCard : Colors.white;
        final mutedColor = isDark
            ? AppColors.textTertiary
            : AppColors.lightTextTertiary;

        return SafeArea(
          child: Container(
            margin: const EdgeInsets.all(12),
            padding: const EdgeInsets.fromLTRB(20, 12, 20, 20),
            decoration: BoxDecoration(
              color: sheetColor,
              borderRadius: BorderRadius.circular(20),
              border: Border.all(
                color: isDark
                    ? AppColors.borderColor
                    : AppColors.lightBorderColor,
              ),
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Center(
                  child: Container(
                    width: 42,
                    height: 4,
                    decoration: BoxDecoration(
                      color: mutedColor.withValues(alpha: 0.45),
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    CircleAvatar(
                      radius: 34,
                      backgroundColor: AppColors.primary.withValues(
                        alpha: 0.18,
                      ),
                      backgroundImage: avatar.isNotEmpty
                          ? NetworkImage(avatar)
                          : null,
                      child: avatar.isEmpty
                          ? Text(
                              _initials(name),
                              style: const TextStyle(
                                color: AppColors.primary,
                                fontWeight: FontWeight.w900,
                                fontSize: 20,
                              ),
                            )
                          : null,
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 10,
                              vertical: 4,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.primary.withValues(alpha: 0.14),
                              borderRadius: BorderRadius.circular(999),
                            ),
                            child: Text(
                              role,
                              style: const TextStyle(
                                color: AppColors.primary,
                                fontSize: 11,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            name,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(
                              color: textColor,
                              fontSize: 20,
                              fontWeight: FontWeight.w800,
                            ),
                          ),
                          if (status.isNotEmpty) ...[
                            const SizedBox(height: 4),
                            Text(
                              _titleCase(status),
                              style: TextStyle(
                                color: mutedColor,
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),
                _buildParticipantDetailRow(
                  icon: Icons.phone_outlined,
                  label: 'Phone',
                  value: phone,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.email_outlined,
                  label: 'Email',
                  value: email,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.location_on_outlined,
                  label: 'Location',
                  value: location,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.badge_outlined,
                  label: 'User ID',
                  value: userId ?? '',
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.group_add_outlined,
                  label: 'Joined Conversation',
                  value: joinedAt,
                  isDark: isDark,
                ),
                const SizedBox(height: 10),
                SizedBox(
                  width: double.infinity,
                  child: OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: textColor,
                      side: BorderSide(
                        color: isDark
                            ? AppColors.borderColor
                            : AppColors.lightBorderColor,
                      ),
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    child: const Text('Close'),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildParticipantDetailRow({
    required IconData icon,
    required String label,
    required String value,
    required bool isDark,
  }) {
    final textColor = isDark
        ? AppColors.textPrimary
        : AppColors.lightTextPrimary;
    final mutedColor = isDark
        ? AppColors.textTertiary
        : AppColors.lightTextTertiary;
    final cleanValue = value.trim().isEmpty ? 'Not provided' : value.trim();

    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkBgSecondary : AppColors.lightBgSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: isDark ? AppColors.borderColor : AppColors.lightBorderColor,
        ),
      ),
      child: Row(
        children: [
          Icon(icon, color: AppColors.primary, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: TextStyle(
                    color: mutedColor,
                    fontSize: 11,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 3),
                Text(
                  cleanValue,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                    color: textColor,
                    fontSize: 13,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _firstValue(Map<String, dynamic> source, List<String> keys) {
    for (final key in keys) {
      final value = source[key]?.toString().trim();
      if (value != null && value.isNotEmpty && value.toLowerCase() != 'null') {
        return value;
      }
    }
    return '';
  }

  String _formatDateTime(String? value) {
    if (value == null || value.trim().isEmpty) return '';
    try {
      final date = DateTime.parse(value).toLocal();
      final minute = date.minute.toString().padLeft(2, '0');
      final hour12 = date.hour % 12 == 0 ? 12 : date.hour % 12;
      final period = date.hour >= 12 ? 'PM' : 'AM';
      return '${date.month}/${date.day}/${date.year}, $hour12:$minute $period';
    } catch (_) {
      return value;
    }
  }

  String _titleCase(String value) {
    return value
        .replaceAll('_', ' ')
        .split(RegExp(r'\s+'))
        .where((part) => part.isNotEmpty)
        .map((part) {
          final lower = part.toLowerCase();
          return '${lower[0].toUpperCase()}${lower.substring(1)}';
        })
        .join(' ');
  }

  String _initials(String name) {
    final parts = name
        .trim()
        .split(RegExp(r'\s+'))
        .where((part) => part.isNotEmpty)
        .toList();
    if (parts.isEmpty) return '?';
    if (parts.length == 1) return parts.first[0].toUpperCase();
    return '${parts.first[0]}${parts.last[0]}'.toUpperCase();
  }
}
