import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../services/chat_service.dart';
import '../../../services/message_filter_service.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_restriction_service.dart';
import '../../theme/app_colors.dart';
import '../../widgets/restriction_ui.dart';
import '../../widgets/optimized_network_image.dart';

class _SupportFaq {
  final String question;
  final String answer;

  const _SupportFaq({required this.question, required this.answer});
}

class ChatDetailScreen extends StatefulWidget {
  final String conversationId;
  final String recipientName;
  final String recipientAvatar;
  final bool isDarkMode;
  final bool isAutoGenerated;
  final bool isCustomerService;
  final String userRole;

  const ChatDetailScreen({
    super.key,
    required this.conversationId,
    required this.recipientName,
    required this.recipientAvatar,
    this.isDarkMode = true,
    this.isAutoGenerated = false,
    this.isCustomerService = false,
    this.userRole = 'renter',
  });

  @override
  State<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

class _ChatDetailScreenState extends State<ChatDetailScreen> {
  late TextEditingController _messageController;
  late Future<List<Map<String, dynamic>>> _messagesFuture;
  late Future<List<Map<String, dynamic>>> _participantsFuture;
  StreamSubscription? _messagesStream;
  String? _warningMessage;
  bool _isLoading = false;
  bool _isUploadingAttachment = false;
  bool _showSupportFaqs = true;
  final AuthService _authService = AuthService();
  final UserRestrictionService _restrictionService = UserRestrictionService();
  UserRestrictionState _restrictionState = UserRestrictionState.empty;
  Timer? _restrictionTicker;

  String get _normalizedRole {
    final role = widget.userRole.trim().toLowerCase();
    if (role == 'partner' || role == 'driver') return role;
    return 'renter';
  }

  String get _roleLabel {
    switch (_normalizedRole) {
      case 'partner':
        return 'partner';
      case 'driver':
        return 'driver';
      default:
        return 'renter';
    }
  }

  List<_SupportFaq> get _supportFaqs {
    switch (_normalizedRole) {
      case 'partner':
        return const [
          _SupportFaq(
            question: 'What documents are needed to become a partner?',
            answer:
                'Complete identity verification and submit the requested business and vehicle ownership records. Vehicle applications normally require clear OR/CR files, ownership or authorization proof, and complete vehicle photos. The review screen will show any additional required document.',
          ),
          _SupportFaq(
            question: 'How do I add a vehicle to Mobilis?',
            answer:
                'Open Manage Fleet, start a vehicle application, complete every vehicle detail, and upload all required photos and documents. The vehicle stays under review until an admin approves it.',
          ),
          _SupportFaq(
            question: 'How can I change my vehicle rental price?',
            answer:
                'Partners cannot directly finalize a price change. Use Customer Service to request the new price. The admin will review it and pass the approved change to the operator.',
          ),
          _SupportFaq(
            question: 'How do availability and active-rental tracking work?',
            answer:
                'Set available dates from Manage Fleet. An unavailable vehicle cannot be booked. During an active approved rental, use the booking Track action to view the latest authorized vehicle location.',
          ),
        ];
      case 'driver':
        return const [
          _SupportFaq(
            question: 'How do I apply as a Mobilis certified driver?',
            answer:
                'Open Application, complete all application steps, review your information, and submit it. Your account remains a basic driver until the application is approved.',
          ),
          _SupportFaq(
            question: 'What documents are required for a driver application?',
            answer:
                'Prepare your valid driver license front and back, license number and expiry date, face selfie, selfie holding your ID, NBI clearance, digital signature, and professional driving information.',
          ),
          _SupportFaq(
            question: 'How do I set my work availability?',
            answer:
                'Open Availability, turn your availability on, and select every date you are available to accept trips. Operators can only assign you for eligible available dates.',
          ),
          _SupportFaq(
            question: 'Where can I see assigned trips and application updates?',
            answer:
                'Assigned trips appear in My Bookings. Application decisions, assignments, document renewal reminders, and trip updates are also sent to Notifications.',
          ),
        ];
      default:
        return const [
          _SupportFaq(
            question: 'How do I rent a vehicle?',
            answer:
                'Verify your account, choose a vehicle, select available dates and service options, complete the required traveler and safety information, then submit the booking and payment details for review.',
          ),
          _SupportFaq(
            question: 'What information is required before booking?',
            answer:
                'You need valid identity verification, the required booking documents, a digital signature, emergency contact details, and complete co-traveler information. A driver license is also required when applicable.',
          ),
          _SupportFaq(
            question: 'How is the vehicle delivery fee calculated?',
            answer:
                'Vehicle delivery costs PHP 75 per kilometer. The booking summary shows the delivery distance, the PHP 75 rate, and the calculated total before confirmation.',
          ),
          _SupportFaq(
            question: 'How do cancellation and refunds work?',
            answer:
                'Open the booking details and use Cancel Request when cancellation is still allowed. The applicable refund depends on the booking status, payment stage, and cancellation rules shown before you confirm.',
          ),
        ];
    }
  }

  @override
  void initState() {
    super.initState();
    _messageController = TextEditingController();
    _loadMessages();
    _loadParticipants();
    _subscribeToMessages();
    _loadRestrictionState();
    unawaited(_markCurrentMessagesRead());
  }

  void _loadMessages() {
    _messagesFuture = ChatService().getMessages(widget.conversationId);
  }

  void _loadParticipants() {
    _participantsFuture = ChatService().getConversationParticipants(
      widget.conversationId,
    );
  }

  void _subscribeToMessages() {
    _messagesStream = ChatService()
        .subscribeToMessages(widget.conversationId)
        .listen(
          (_) {
            if (!mounted) return;
            setState(() {
              _loadMessages();
            });
            unawaited(_markCurrentMessagesRead());
          },
          onError: (Object error) {
            debugPrint('Message realtime subscription failed: $error');
          },
        );
  }

  Future<void> _markCurrentMessagesRead() async {
    final userId = _authService.currentUser?.id;
    if (userId == null || widget.conversationId.trim().isEmpty) return;
    try {
      await ChatService().markMessagesAsRead(widget.conversationId, userId);
    } catch (e) {
      debugPrint('Could not mark conversation as read: $e');
    }
  }

  Future<void> _loadRestrictionState() async {
    final state = await _restrictionService.getCurrentUserRestriction();
    if (!mounted) return;
    setState(() {
      _restrictionState = state;
    });
    _restartRestrictionTicker();
  }

  void _restartRestrictionTicker() {
    _restrictionTicker?.cancel();
    if (!_restrictionState.isMessagingRestricted) return;

    _restrictionTicker = Timer.periodic(const Duration(seconds: 1), (_) {
      if (!mounted) return;
      setState(() {});
      if (!_restrictionState.isMessagingRestricted) {
        _restrictionTicker?.cancel();
      }
    });
  }

  Future<void> _sendMessage() async {
    if (_messageController.text.trim().isEmpty) return;
    if (_restrictionState.isMessagingRestricted) {
      setState(() {
        _warningMessage =
            'Messaging is temporarily restricted. Please wait for the timer to expire before sending another message.';
      });
      return;
    }

    final messageContent = _messageController.text.trim();
    final currentUser = _authService.currentUser;

    if (currentUser == null) return;

    setState(() => _isLoading = true);

    try {
      // Analyze message for off-platform transaction attempts
      final analysis = MessageFilterService.analyzeMessage(messageContent);

      // Show warning if suspicious
      if (analysis['is_suspicious']) {
        setState(() {
          _warningMessage = analysis['risk_level'] == 'high'
              ? '⚠️ This message may contain contact details. Keep payments within the app for security.'
              : 'ℹ️ Reminder: Keep all transactions within the app for protection.';
        });
      } else {
        setState(() => _warningMessage = null);
      }

      // Send message
      final sentMessage = await ChatService().sendMessage(
        conversationId: widget.conversationId,
        senderId: currentUser.id,
        content: messageContent,
      );

      // Flag if necessary
      if (analysis['should_flag']) {
        final messageId =
            sentMessage['id']?.toString() ??
            DateTime.now().millisecondsSinceEpoch.toString();
        await MessageFilterService.flagMessageForReview(
          messageId: messageId,
          conversationId: widget.conversationId,
          senderId: currentUser.id,
          flagReason:
              'Potential off-platform transaction attempt: ${analysis['found_keywords'].join(', ')}',
          messageContent: messageContent,
        );
        await _restrictionService.applyPolicyViolation(
          userId: currentUser.id,
          conversationId: widget.conversationId,
        );

        // Show flag notification
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                '📋 Message has been flagged for safety review. Keep transactions within the app.',
              ),
              duration: Duration(seconds: 3),
              backgroundColor: AppColors.warning,
            ),
          );
        }
      }

      _messageController.clear();
      if (mounted) {
        setState(() {
          _loadMessages();
          _loadParticipants();
        });
      }
      await _loadRestrictionState();

      if (mounted) {
        setState(() => _isLoading = false);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to send message: $e'),
            backgroundColor: AppColors.error,
          ),
        );
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _pickAndSendAttachment() async {
    if (_restrictionState.isMessagingRestricted || _isUploadingAttachment) {
      return;
    }

    final currentUser = _authService.currentUser;
    if (currentUser == null) return;

    final result = await FilePicker.platform.pickFiles(
      type: FileType.any,
      withData: false,
    );
    final picked = result?.files.single;
    final path = picked?.path;
    if (picked == null || path == null || path.isEmpty) return;

    setState(() {
      _isUploadingAttachment = true;
      _warningMessage = null;
    });

    try {
      final file = File(path);
      final url = await ChatService().uploadChatAttachment(
        senderId: currentUser.id,
        file: file,
        fileName: picked.name,
      );
      final type = _attachmentTypeForName(picked.name);

      await ChatService().sendMessage(
        conversationId: widget.conversationId,
        senderId: currentUser.id,
        content: 'Sent an attachment: ${picked.name}',
        attachmentUrl: url,
        attachmentType: type,
        attachmentName: picked.name,
        attachmentSize: picked.size,
      );

      if (mounted) {
        setState(() {
          _loadMessages();
          _loadParticipants();
        });
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to send attachment: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isUploadingAttachment = false;
        });
      }
    }
  }

  String _attachmentTypeForName(String fileName) {
    final lower = fileName.toLowerCase();
    if (lower.endsWith('.jpg') ||
        lower.endsWith('.jpeg') ||
        lower.endsWith('.png') ||
        lower.endsWith('.webp')) {
      return 'image';
    }
    if (lower.endsWith('.mp4') ||
        lower.endsWith('.mov') ||
        lower.endsWith('.avi')) {
      return 'video';
    }
    return 'document';
  }

  IconData _attachmentIcon(String type) {
    switch (type) {
      case 'image':
        return Icons.image_outlined;
      case 'video':
        return Icons.videocam_outlined;
      default:
        return Icons.insert_drive_file_outlined;
    }
  }

  void _showFaqAnswer(_SupportFaq faq) {
    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (sheetContext) => SafeArea(
        child: Container(
          margin: const EdgeInsets.all(12),
          padding: const EdgeInsets.fromLTRB(20, 12, 20, 20),
          decoration: BoxDecoration(
            color: AppColors.darkCard,
            borderRadius: BorderRadius.circular(18),
            border: Border.all(color: AppColors.borderColor),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Container(
                  width: 42,
                  height: 4,
                  decoration: BoxDecoration(
                    color: AppColors.textTertiary.withValues(alpha: 0.45),
                    borderRadius: BorderRadius.circular(4),
                  ),
                ),
              ),
              const SizedBox(height: 18),
              const Row(
                children: [
                  Icon(Icons.support_agent_outlined, color: AppColors.primary),
                  SizedBox(width: 10),
                  Text(
                    'Mobilis Help',
                    style: TextStyle(
                      color: AppColors.textPrimary,
                      fontSize: 16,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 18),
              Text(
                faq.question,
                style: const TextStyle(
                  color: AppColors.textPrimary,
                  fontSize: 16,
                  fontWeight: FontWeight.w800,
                  height: 1.3,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                faq.answer,
                style: const TextStyle(
                  color: AppColors.textSecondary,
                  fontSize: 13,
                  height: 1.55,
                ),
              ),
              const SizedBox(height: 22),
              SizedBox(
                width: double.infinity,
                child: FilledButton.icon(
                  onPressed: () {
                    Navigator.pop(sheetContext);
                    setState(() => _showSupportFaqs = false);
                    _messageController
                      ..text = faq.question
                      ..selection = TextSelection.collapsed(
                        offset: faq.question.length,
                      );
                  },
                  icon: const Icon(Icons.chat_bubble_outline),
                  label: const Text('Ask the admin about this'),
                  style: FilledButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.black,
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildCustomerServicePanel() {
    if (MediaQuery.viewInsetsOf(context).bottom > 0) {
      return const SizedBox.shrink();
    }

    return Container(
      width: double.infinity,
      margin: const EdgeInsets.fromLTRB(12, 12, 12, 4),
      decoration: BoxDecoration(
        color: AppColors.darkCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppColors.borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(14, 14, 8, 12),
            child: Row(
              children: [
                Container(
                  width: 42,
                  height: 42,
                  decoration: BoxDecoration(
                    color: AppColors.primary.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(11),
                  ),
                  child: const Icon(
                    Icons.support_agent,
                    color: AppColors.primary,
                  ),
                ),
                const SizedBox(width: 12),
                const Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'How can we help?',
                        style: TextStyle(
                          color: AppColors.textPrimary,
                          fontSize: 15,
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                      SizedBox(height: 3),
                      Text(
                        'Your messages are received by the admin support team.',
                        style: TextStyle(
                          color: AppColors.textSecondary,
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                ),
                IconButton(
                  tooltip: _showSupportFaqs ? 'Hide FAQs' : 'Show FAQs',
                  onPressed: () =>
                      setState(() => _showSupportFaqs = !_showSupportFaqs),
                  icon: Icon(
                    _showSupportFaqs
                        ? Icons.keyboard_arrow_up
                        : Icons.keyboard_arrow_down,
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
            ),
          ),
          if (_showSupportFaqs) ...[
            const Divider(height: 1, color: AppColors.borderColor),
            Padding(
              padding: const EdgeInsets.fromLTRB(14, 12, 14, 6),
              child: Text(
                'Frequently asked questions for $_roleLabel accounts',
                style: const TextStyle(
                  color: AppColors.textPrimary,
                  fontSize: 12,
                  fontWeight: FontWeight.w800,
                ),
              ),
            ),
            ConstrainedBox(
              constraints: const BoxConstraints(maxHeight: 210),
              child: ListView.separated(
                shrinkWrap: true,
                padding: const EdgeInsets.fromLTRB(8, 0, 8, 8),
                itemCount: _supportFaqs.length,
                separatorBuilder: (_, _) => const Divider(
                  height: 1,
                  indent: 8,
                  endIndent: 8,
                  color: AppColors.borderColor,
                ),
                itemBuilder: (context, index) {
                  final faq = _supportFaqs[index];
                  return InkWell(
                    onTap: () => _showFaqAnswer(faq),
                    borderRadius: BorderRadius.circular(10),
                    child: Padding(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 11,
                      ),
                      child: Row(
                        children: [
                          Expanded(
                            child: Text(
                              faq.question,
                              style: const TextStyle(
                                color: AppColors.primary,
                                fontSize: 12,
                                fontWeight: FontWeight.w700,
                                height: 1.35,
                              ),
                            ),
                          ),
                          const SizedBox(width: 8),
                          const Icon(
                            Icons.chevron_right,
                            color: AppColors.textTertiary,
                            size: 20,
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ],
      ),
    );
  }

  @override
  void dispose() {
    _messageController.dispose();
    _messagesStream?.cancel();
    _restrictionTicker?.cancel();
    super.dispose();
  }

  Widget _buildCustomerServiceAppBarTitle() {
    return Row(
      children: [
        Container(
          width: 34,
          height: 34,
          decoration: BoxDecoration(
            color: Colors.black.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(9),
          ),
          child: const Icon(Icons.support_agent, color: Colors.black, size: 20),
        ),
        const SizedBox(width: 10),
        const Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Customer Service',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.w800,
                  fontSize: 16,
                ),
              ),
              Text(
                'Admin support',
                style: TextStyle(
                  color: Colors.black87,
                  fontWeight: FontWeight.w500,
                  fontSize: 10,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark =
        widget.isCustomerService ||
        widget.isDarkMode ||
        Theme.of(context).brightness == Brightness.dark;
    final bgColor = isDark ? AppColors.darkBg : AppColors.lightBg;
    final cardColor = isDark ? AppColors.darkCard : Colors.white;
    final textColor = isDark
        ? AppColors.textPrimary
        : AppColors.lightTextPrimary;
    final appBarColor = widget.isCustomerService ? AppColors.primary : bgColor;
    final appBarTextColor = widget.isCustomerService ? Colors.black : textColor;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        backgroundColor: appBarColor,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: appBarTextColor),
          onPressed: () => Navigator.pop(context),
        ),
        title: widget.isCustomerService
            ? _buildCustomerServiceAppBarTitle()
            : Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      if (widget.isAutoGenerated)
                        Container(
                          margin: const EdgeInsets.only(right: 8),
                          padding: const EdgeInsets.symmetric(
                            horizontal: 6,
                            vertical: 2,
                          ),
                          decoration: BoxDecoration(
                            color: AppColors.success.withValues(alpha: 0.2),
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: const Text(
                            '🤖 Auto',
                            style: TextStyle(
                              fontSize: 10,
                              color: AppColors.success,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      Text(
                        widget.recipientName,
                        style: TextStyle(
                          color: textColor,
                          fontWeight: FontWeight.w600,
                          fontSize: 16,
                        ),
                      ),
                    ],
                  ),
                  if (widget.isAutoGenerated)
                    Text(
                      'Conversation created automatically on booking confirmation',
                      style: TextStyle(
                        fontSize: 11,
                        color: isDark
                            ? AppColors.textTertiary
                            : AppColors.lightTextTertiary,
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                ],
              ),
        actions: [
          IconButton(
            onPressed: () => showPolicyDetailsSheet(context),
            icon: Icon(Icons.info_outline, color: appBarTextColor),
          ),
        ],
      ),
      body: Column(
        children: [
          if (widget.isCustomerService)
            _buildCustomerServicePanel()
          else
            _buildParticipantReference(isDark, cardColor, textColor),
          if (_restrictionState.isMessagingRestricted)
            _buildRestrictionBanner(),

          // Messages list
          Expanded(
            child: FutureBuilder<List<Map<String, dynamic>>>(
              future: _messagesFuture,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Padding(
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(
                            Icons.error_outline,
                            color: AppColors.error,
                            size: 34,
                          ),
                          const SizedBox(height: 10),
                          Text(
                            'Could not load this conversation',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: textColor,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          const SizedBox(height: 12),
                          OutlinedButton.icon(
                            onPressed: () => setState(_loadMessages),
                            icon: const Icon(Icons.refresh),
                            label: const Text('Retry'),
                          ),
                        ],
                      ),
                    ),
                  );
                }

                final messages = snapshot.data ?? [];

                if (messages.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        if (widget.isAutoGenerated)
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 24,
                              vertical: 16,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.success.withValues(alpha: 0.1),
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(
                                color: AppColors.success,
                                width: 1,
                              ),
                            ),
                            child: Column(
                              children: [
                                Icon(
                                  Icons.check_circle,
                                  color: AppColors.success,
                                  size: 32,
                                ),
                                const SizedBox(height: 8),
                                Text(
                                  'Conversation Started',
                                  style: TextStyle(
                                    fontSize: 14,
                                    fontWeight: FontWeight.w600,
                                    color: textColor,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  'This conversation was automatically created when the booking was confirmed. Start messaging now!',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: isDark
                                        ? AppColors.textSecondary
                                        : AppColors.lightTextSecondary,
                                  ),
                                ),
                              ],
                            ),
                          )
                        else
                          Icon(
                            Icons.chat_bubble_outline,
                            size: 48,
                            color: isDark
                                ? AppColors.textTertiary
                                : AppColors.lightTextTertiary,
                          ),
                        const SizedBox(height: 12),
                        Text(
                          widget.isCustomerService
                              ? 'No support messages yet'
                              : 'No messages yet',
                          style: TextStyle(color: textColor),
                        ),
                        if (widget.isCustomerService) ...[
                          const SizedBox(height: 6),
                          const Padding(
                            padding: EdgeInsets.symmetric(horizontal: 28),
                            child: Text(
                              'Choose an FAQ above or type your inquiry below. Your message goes directly to admin support.',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: AppColors.textSecondary,
                                fontSize: 11,
                                height: 1.4,
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  );
                }

                return ListView.builder(
                  reverse: true,
                  padding: const EdgeInsets.all(16),
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    final message = messages[messages.length - 1 - index];
                    final isAutoGenerated =
                        message['is_auto_generated'] == true;
                    final currentUserId = _authService.currentUser?.id;
                    final isCurrentUser = message['sender_id'] == currentUserId;
                    final content =
                        (message['content'] ?? message['message'] ?? '')
                            .toString();
                    final attachmentUrl = message['attachment_url']?.toString();
                    final attachmentName =
                        message['attachment_name']?.toString() ?? 'Attachment';
                    final attachmentType =
                        message['attachment_type']?.toString() ?? 'document';
                    final violatesPolicy =
                        isCurrentUser &&
                        MessageFilterService.analyzeMessage(
                              content,
                            )['should_flag'] ==
                            true;

                    return Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Column(
                        crossAxisAlignment: isCurrentUser
                            ? CrossAxisAlignment.end
                            : CrossAxisAlignment.start,
                        children: [
                          // Auto-message badge
                          if (isAutoGenerated)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 4),
                              child: Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                decoration: BoxDecoration(
                                  color: AppColors.primary.withValues(
                                    alpha: 0.1,
                                  ),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: const Text(
                                  '🤖 Auto-generated message',
                                  style: TextStyle(
                                    fontSize: 10,
                                    color: AppColors.primary,
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                              ),
                            ),
                          // Message bubble
                          Container(
                            constraints: const BoxConstraints(maxWidth: 280),
                            padding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 8,
                            ),
                            decoration: BoxDecoration(
                              color: isCurrentUser
                                  ? AppColors.primary
                                  : (isDark
                                        ? AppColors.darkBgSecondary
                                        : Colors.grey[200]),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                if (attachmentUrl != null &&
                                    attachmentUrl.isNotEmpty) ...[
                                  InkWell(
                                    onTap: () => launchUrl(
                                      Uri.parse(attachmentUrl),
                                      mode: LaunchMode.externalApplication,
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Icon(
                                          _attachmentIcon(attachmentType),
                                          color: isCurrentUser
                                              ? Colors.black
                                              : AppColors.primary,
                                          size: 18,
                                        ),
                                        const SizedBox(width: 8),
                                        Flexible(
                                          child: Text(
                                            attachmentName,
                                            maxLines: 2,
                                            overflow: TextOverflow.ellipsis,
                                            style: TextStyle(
                                              fontSize: 13,
                                              fontWeight: FontWeight.w700,
                                              color: isCurrentUser
                                                  ? Colors.black
                                                  : (isDark
                                                        ? AppColors.textPrimary
                                                        : Colors.black),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  if (content.isNotEmpty)
                                    const SizedBox(height: 8),
                                ],
                                if (content.isNotEmpty)
                                  Text(
                                    content,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: isCurrentUser
                                          ? Colors.black
                                          : (isDark
                                                ? AppColors.textPrimary
                                                : Colors.black),
                                    ),
                                  ),
                              ],
                            ),
                          ),
                          // Timestamp
                          Padding(
                            padding: const EdgeInsets.only(top: 4),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Text(
                                  _formatTime(message['created_at']),
                                  style: TextStyle(
                                    fontSize: 11,
                                    color: isDark
                                        ? AppColors.textTertiary
                                        : AppColors.lightTextTertiary,
                                  ),
                                ),
                                if (violatesPolicy) ...[
                                  const SizedBox(width: 8),
                                  const Text(
                                    'Violates policy',
                                    style: TextStyle(
                                      fontSize: 11,
                                      color: Color(0xFFFF5B5B),
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ],
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                );
              },
            ),
          ),

          // Warning message
          if (_warningMessage != null)
            Container(
              margin: const EdgeInsets.all(12),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppColors.warning.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppColors.warning),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.warning_outlined,
                    color: AppColors.warning,
                    size: 18,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      _warningMessage!,
                      style: const TextStyle(
                        fontSize: 12,
                        color: AppColors.warning,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ],
              ),
            ),

          // Message input
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: cardColor,
              border: Border(
                top: BorderSide(
                  color: isDark
                      ? AppColors.borderColor
                      : AppColors.lightBorderColor,
                ),
              ),
            ),
            child: Row(
              children: [
                IconButton(
                  tooltip: 'Attach file',
                  onPressed:
                      _isLoading ||
                          _isUploadingAttachment ||
                          _restrictionState.isMessagingRestricted
                      ? null
                      : _pickAndSendAttachment,
                  icon: _isUploadingAttachment
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: AppColors.primary,
                          ),
                        )
                      : const Icon(
                          Icons.add_circle_outline,
                          color: AppColors.primary,
                        ),
                ),
                const SizedBox(width: 4),
                Expanded(
                  child: TextField(
                    controller: _messageController,
                    maxLines: 3,
                    minLines: 1,
                    enabled:
                        !_isLoading && !_restrictionState.isMessagingRestricted,
                    decoration: InputDecoration(
                      hintText: _restrictionState.isMessagingRestricted
                          ? 'Messaging restricted'
                          : widget.isCustomerService
                          ? 'Type your question for admin...'
                          : 'Type your message...',
                      hintStyle: TextStyle(
                        color: isDark
                            ? AppColors.textTertiary
                            : AppColors.lightTextTertiary,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: BorderSide(
                          color: isDark
                              ? AppColors.borderColor
                              : AppColors.lightBorderColor,
                        ),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 8,
                      ),
                    ),
                    style: TextStyle(color: textColor),
                  ),
                ),
                const SizedBox(width: 8),
                Container(
                  decoration: BoxDecoration(
                    color: _restrictionState.isMessagingRestricted
                        ? AppColors.darkBgTertiary
                        : AppColors.primary,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: IconButton(
                    icon: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color>(
                                Colors.black,
                              ),
                            ),
                          )
                        : Icon(
                            _restrictionState.isMessagingRestricted
                                ? Icons.lock_outline
                                : Icons.send,
                            color: _restrictionState.isMessagingRestricted
                                ? AppColors.textSecondary
                                : Colors.black,
                          ),
                    onPressed:
                        _isLoading || _restrictionState.isMessagingRestricted
                        ? null
                        : _sendMessage,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildRestrictionBanner() {
    final isAccountLevel =
        _restrictionState.isAccountRestricted || _restrictionState.isBlocked;
    final description = _restrictionState.isBlocked
        ? 'You cannot send messages because this account has been permanently blocked after repeated policy violations.'
        : _restrictionState.level == 'second_attempt'
        ? 'You cannot send messages because this account is under a 1-month policy restriction after a repeated off-platform violation.'
        : 'You cannot send messages because this account is under a 1-week policy restriction after an off-platform violation.';

    return Container(
      width: double.infinity,
      margin: const EdgeInsets.fromLTRB(16, 14, 16, 10),
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: const Color(0xFF2A1B24),
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFB53845)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            isAccountLevel
                ? 'System Alert: Account Restricted'
                : 'System Alert: Restricted Access',
            style: const TextStyle(
              color: Color(0xFFFF5B5B),
              fontSize: 16,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 12),
          Text(
            description,
            style: const TextStyle(color: AppColors.textPrimary, height: 1.5),
          ),
          const SizedBox(height: 6),
          const Text(
            'Our safety team monitors all conversations to protect our community.',
            style: TextStyle(color: AppColors.textSecondary, height: 1.5),
          ),
          const SizedBox(height: 10),
          GestureDetector(
            onTap: () => showPolicyDetailsSheet(context),
            child: const Text(
              'View Policy Details',
              style: TextStyle(
                color: AppColors.primary,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          if (!_restrictionState.isBlocked) ...[
            const SizedBox(height: 18),
            const Center(
              child: Text(
                'RESTRICTION EXPIRES IN',
                style: TextStyle(
                  color: AppColors.textSecondary,
                  fontSize: 12,
                  letterSpacing: 1.1,
                ),
              ),
            ),
            const SizedBox(height: 12),
            RestrictionCountdownRow(
              until: _restrictionState.activeUntil,
              includeSeconds: true,
            ),
          ] else ...[
            const SizedBox(height: 18),
            const Center(
              child: Text(
                'PERMANENT ACCOUNT BLOCK',
                style: TextStyle(
                  color: Color(0xFFFF5B5B),
                  fontSize: 12,
                  letterSpacing: 1.1,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  String _formatTime(String? dateString) {
    if (dateString == null) return '';
    try {
      final date = DateTime.parse(dateString);
      final now = DateTime.now();
      final diff = now.difference(date);

      if (diff.inMinutes < 1) return 'now';
      if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
      if (diff.inHours < 24) return '${diff.inHours}h ago';
      if (diff.inDays < 7) return '${diff.inDays}d ago';

      return '${date.day}/${date.month}';
    } catch (e) {
      return '';
    }
  }

  Widget _buildParticipantReference(
    bool isDark,
    Color cardColor,
    Color textColor,
  ) {
    return FutureBuilder<List<Map<String, dynamic>>>(
      future: _participantsFuture,
      builder: (context, snapshot) {
        final participants = snapshot.data ?? [];

        if (snapshot.connectionState == ConnectionState.waiting) {
          return Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              color: cardColor,
              border: Border(
                bottom: BorderSide(
                  color: isDark
                      ? AppColors.borderColor
                      : AppColors.lightBorderColor,
                ),
              ),
            ),
            child: const SizedBox(
              height: 42,
              child: Align(
                alignment: Alignment.centerLeft,
                child: SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ),
            ),
          );
        }

        if (participants.isEmpty) {
          return const SizedBox.shrink();
        }

        return Container(
          width: double.infinity,
          padding: const EdgeInsets.fromLTRB(16, 10, 16, 12),
          decoration: BoxDecoration(
            color: cardColor,
            border: Border(
              bottom: BorderSide(
                color: isDark
                    ? AppColors.borderColor
                    : AppColors.lightBorderColor,
              ),
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Booking participants',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: isDark
                      ? AppColors.textSecondary
                      : AppColors.lightTextSecondary,
                ),
              ),
              const SizedBox(height: 8),
              SizedBox(
                height: 92,
                child: ListView.separated(
                  scrollDirection: Axis.horizontal,
                  itemCount: participants.length,
                  separatorBuilder: (_, _) => const SizedBox(width: 10),
                  itemBuilder: (context, index) {
                    return _buildParticipantCard(
                      participants[index],
                      isDark,
                      textColor,
                    );
                  },
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildParticipantCard(
    Map<String, dynamic> participant,
    bool isDark,
    Color textColor,
  ) {
    final name =
        participant['display_name']?.toString().trim().isNotEmpty == true
        ? participant['display_name'].toString().trim()
        : 'Unknown User';
    final role =
        participant['display_role']?.toString().trim().isNotEmpty == true
        ? participant['display_role'].toString().trim()
        : 'Participant';
    final email = participant['email']?.toString().trim() ?? '';
    final phone = participant['display_phone']?.toString().trim() ?? '';
    final avatar = participant['display_avatar']?.toString().trim() ?? '';
    final subtitle = phone.isNotEmpty
        ? phone
        : email.isNotEmpty
        ? email
        : 'No contact saved';

    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(10),
        onTap: () => _showParticipantDetails(participant, isDark, textColor),
        child: Ink(
          width: 230,
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: isDark
                ? AppColors.darkBgSecondary
                : AppColors.lightBgSecondary,
            borderRadius: BorderRadius.circular(10),
            border: Border.all(
              color: isDark
                  ? AppColors.borderColor
                  : AppColors.lightBorderColor,
            ),
          ),
          child: Row(
            children: [
              Container(
                width: 48,
                height: 48,
                alignment: Alignment.center,
                decoration: BoxDecoration(
                  color: AppColors.primary.withValues(alpha: 0.18),
                  borderRadius: BorderRadius.circular(14),
                  image: avatar.isNotEmpty
                      ? DecorationImage(
                          image: OptimizedNetworkImageProvider(avatar),
                          fit: BoxFit.cover,
                        )
                      : null,
                ),
                child: avatar.isEmpty
                    ? Text(
                        _initials(name),
                        style: const TextStyle(
                          color: AppColors.primary,
                          fontWeight: FontWeight.w800,
                        ),
                      )
                    : null,
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      role,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.w800,
                        color: AppColors.primary,
                      ),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w700,
                        color: textColor,
                      ),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      subtitle,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        fontSize: 11,
                        color: isDark
                            ? AppColors.textTertiary
                            : AppColors.lightTextTertiary,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(
                Icons.info_outline,
                size: 18,
                color: isDark
                    ? AppColors.textTertiary
                    : AppColors.lightTextTertiary,
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _showParticipantDetails(
    Map<String, dynamic> participant,
    bool isDark,
    Color textColor,
  ) {
    final name =
        participant['display_name']?.toString().trim().isNotEmpty == true
        ? participant['display_name'].toString().trim()
        : 'Unknown User';
    final role =
        participant['display_role']?.toString().trim().isNotEmpty == true
        ? participant['display_role'].toString().trim()
        : 'Participant';
    final avatar = participant['display_avatar']?.toString().trim() ?? '';
    final email = participant['email']?.toString().trim() ?? '';
    final phone = participant['display_phone']?.toString().trim() ?? '';
    final location = _firstValue(participant, [
      'location',
      'address',
      'city',
      'province',
    ]);
    final status = _firstValue(participant, [
      'status',
      'verification_status',
      'account_status',
    ]);
    final userId =
        participant['user_id']?.toString() ?? participant['id']?.toString();
    final joinedAt = _formatDateTime(participant['joined_at']?.toString());

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final sheetColor = isDark ? AppColors.darkCard : Colors.white;
        final mutedColor = isDark
            ? AppColors.textTertiary
            : AppColors.lightTextTertiary;

        return SafeArea(
          child: Container(
            margin: const EdgeInsets.all(12),
            padding: const EdgeInsets.fromLTRB(20, 12, 20, 20),
            decoration: BoxDecoration(
              color: sheetColor,
              borderRadius: BorderRadius.circular(20),
              border: Border.all(
                color: isDark
                    ? AppColors.borderColor
                    : AppColors.lightBorderColor,
              ),
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Center(
                  child: Container(
                    width: 42,
                    height: 4,
                    decoration: BoxDecoration(
                      color: mutedColor.withValues(alpha: 0.45),
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Container(
                      width: 68,
                      height: 68,
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        color: AppColors.primary.withValues(alpha: 0.18),
                        borderRadius: BorderRadius.circular(18),
                        image: avatar.isNotEmpty
                            ? DecorationImage(
                                image: OptimizedNetworkImageProvider(avatar),
                                fit: BoxFit.cover,
                              )
                            : null,
                      ),
                      child: avatar.isEmpty
                          ? Text(
                              _initials(name),
                              style: const TextStyle(
                                color: AppColors.primary,
                                fontWeight: FontWeight.w900,
                                fontSize: 20,
                              ),
                            )
                          : null,
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 10,
                              vertical: 4,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.primary.withValues(alpha: 0.14),
                              borderRadius: BorderRadius.circular(999),
                            ),
                            child: Text(
                              role,
                              style: const TextStyle(
                                color: AppColors.primary,
                                fontSize: 11,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            name,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(
                              color: textColor,
                              fontSize: 20,
                              fontWeight: FontWeight.w800,
                            ),
                          ),
                          if (status.isNotEmpty) ...[
                            const SizedBox(height: 4),
                            Text(
                              _titleCase(status),
                              style: TextStyle(
                                color: mutedColor,
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),
                _buildParticipantDetailRow(
                  icon: Icons.phone_outlined,
                  label: 'Phone',
                  value: phone,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.email_outlined,
                  label: 'Email',
                  value: email,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.location_on_outlined,
                  label: 'Location',
                  value: location,
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.badge_outlined,
                  label: 'User ID',
                  value: userId ?? '',
                  isDark: isDark,
                ),
                _buildParticipantDetailRow(
                  icon: Icons.group_add_outlined,
                  label: 'Joined Conversation',
                  value: joinedAt,
                  isDark: isDark,
                ),
                const SizedBox(height: 10),
                SizedBox(
                  width: double.infinity,
                  child: OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: textColor,
                      side: BorderSide(
                        color: isDark
                            ? AppColors.borderColor
                            : AppColors.lightBorderColor,
                      ),
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    child: const Text('Close'),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildParticipantDetailRow({
    required IconData icon,
    required String label,
    required String value,
    required bool isDark,
  }) {
    final textColor = isDark
        ? AppColors.textPrimary
        : AppColors.lightTextPrimary;
    final mutedColor = isDark
        ? AppColors.textTertiary
        : AppColors.lightTextTertiary;
    final cleanValue = value.trim().isEmpty ? 'Not provided' : value.trim();

    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkBgSecondary : AppColors.lightBgSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: isDark ? AppColors.borderColor : AppColors.lightBorderColor,
        ),
      ),
      child: Row(
        children: [
          Icon(icon, color: AppColors.primary, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: TextStyle(
                    color: mutedColor,
                    fontSize: 11,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 3),
                Text(
                  cleanValue,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                    color: textColor,
                    fontSize: 13,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _firstValue(Map<String, dynamic> source, List<String> keys) {
    for (final key in keys) {
      final value = source[key]?.toString().trim();
      if (value != null && value.isNotEmpty && value.toLowerCase() != 'null') {
        return value;
      }
    }
    return '';
  }

  String _formatDateTime(String? value) {
    if (value == null || value.trim().isEmpty) return '';
    try {
      final date = DateTime.parse(value).toLocal();
      final minute = date.minute.toString().padLeft(2, '0');
      final hour12 = date.hour % 12 == 0 ? 12 : date.hour % 12;
      final period = date.hour >= 12 ? 'PM' : 'AM';
      return '${date.month}/${date.day}/${date.year}, $hour12:$minute $period';
    } catch (_) {
      return value;
    }
  }

  String _titleCase(String value) {
    return value
        .replaceAll('_', ' ')
        .split(RegExp(r'\s+'))
        .where((part) => part.isNotEmpty)
        .map((part) {
          final lower = part.toLowerCase();
          return '${lower[0].toUpperCase()}${lower.substring(1)}';
        })
        .join(' ');
  }

  String _initials(String name) {
    final parts = name
        .trim()
        .split(RegExp(r'\s+'))
        .where((part) => part.isNotEmpty)
        .toList();
    if (parts.isEmpty) return '?';
    if (parts.length == 1) return parts.first[0].toUpperCase();
    return '${parts.first[0]}${parts.last[0]}'.toUpperCase();
  }
}
