import 'package:supabase_flutter/supabase_flutter.dart';

class AutoMessageService {
  static final supabase = Supabase.instance.client;

  /// Create conversation and initial auto-message when booking is confirmed
  static Future<Map<String, dynamic>> createBookingConversation({
    required String bookingId,
    required String renterId,
    required String recipientId, // Partner or Driver
    required String vehicleTitle,
    required String pickupDate,
    required String dropoffDate,
  }) async {
    try {
      // Check if conversation already exists
      final existingConv = await supabase
          .from('conversations')
          .select('id')
          .eq('booking_id', bookingId)
          .maybeSingle();

      if (existingConv != null) {
        return {
          'success': true,
          'already_exists': true,
          'conversation_id': existingConv['id'],
        };
      }

      // Create conversation
      final convResponse = await supabase
          .from('conversations')
          .insert({
            'booking_id': bookingId,
            'user_id': renterId,
            'other_user_id': recipientId,
            'created_at': DateTime.now().toIso8601String(),
          })
          .select()
          .single();

      final conversationId = convResponse['id'];

      // Create auto-message
      final autoMessage = _buildAutoMessage(
        vehicleTitle: vehicleTitle,
        pickupDate: pickupDate,
        dropoffDate: dropoffDate,
      );

      await supabase.from('messages').insert({
        'conversation_id': conversationId,
        'sender_id': 'system', // Special sender ID for auto-messages
        'content': autoMessage,
        'is_auto_generated': true,
        'created_at': DateTime.now().toIso8601String(),
      });

      return {
        'success': true,
        'already_exists': false,
        'conversation_id': conversationId,
        'message': 'Conversation created with auto-message',
      };
    } catch (e) {
      return {'success': false, 'error': 'Failed to create conversation: $e'};
    }
  }

  /// Build auto-message content
  static String _buildAutoMessage({
    required String vehicleTitle,
    required String pickupDate,
    required String dropoffDate,
  }) {
    return '''📋 **Booking Confirmed**

Your booking for **$vehicleTitle** is confirmed!

🗓️ **Rental Period**
• Pickup: $pickupDate
• Dropoff: $dropoffDate

💬 **How this works:**
• Use this chat to communicate about pickup/dropoff details
• All conversations are monitored for safety and security
• Keep payments and booking details within the app
• Users attempting to conduct business outside the app may be restricted

⚠️ **Important Reminders:**
✓ Always complete payments through the app for protection
✓ Do not share personal contact details unless necessary
✓ Report any suspicious requests to support
✓ All bookings are covered by our insurance & protection plan

Questions? Feel free to message here!
''';
  }

  /// Get all auto-generated messages in conversation
  static Future<List<Map<String, dynamic>>> getAutoMessages(
    String conversationId,
  ) async {
    try {
      return await supabase
          .from('messages')
          .select()
          .eq('conversation_id', conversationId)
          .eq('is_auto_generated', true)
          .order('created_at', ascending: false);
    } catch (e) {
      return [];
    }
  }

  /// Check if conversation is auto-generated
  static Future<bool> isConversationAutoGenerated(String conversationId) async {
    try {
      final autoMessages = await getAutoMessages(conversationId);
      return autoMessages.isNotEmpty;
    } catch (e) {
      return false;
    }
  }
}
