import 'dart:async';

import 'package:flutter/material.dart';

import '../../../services/tracking_service.dart';
import '../../theme/app_colors.dart';
import '../../widgets/leaflet_map.dart';
import '../home/chat_detail_screen.dart';

class PartnerTrackingScreen extends StatefulWidget {
  final Map<String, dynamic> booking;
  final String conversationId;
  final String recipientName;

  const PartnerTrackingScreen({
    super.key,
    required this.booking,
    required this.conversationId,
    required this.recipientName,
  });

  @override
  State<PartnerTrackingScreen> createState() => _PartnerTrackingScreenState();
}

class _PartnerTrackingScreenState extends State<PartnerTrackingScreen> {
  final TrackingService _trackingService = TrackingService();
  Timer? _refreshTimer;
  Map<String, dynamic>? _trackingLocation;
  bool _isLoading = true;
  double _zoom = 12;

  @override
  void initState() {
    super.initState();
    _loadTrackingLocation();
    _refreshTimer = Timer.periodic(const Duration(seconds: 20), (_) {
      _loadTrackingLocation(showLoader: false);
    });
  }

  @override
  void dispose() {
    _refreshTimer?.cancel();
    super.dispose();
  }

  Future<void> _loadTrackingLocation({bool showLoader = true}) async {
    if (showLoader && mounted) {
      setState(() => _isLoading = true);
    }

    final bookingId = widget.booking['id']?.toString() ?? '';
    final location = await _trackingService.getTrackingLocationForBooking(
      bookingId,
    );

    if (!mounted) return;
    setState(() {
      _trackingLocation = location;
      _isLoading = false;
    });
  }

  Future<void> _openConversation() async {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (_) => ChatDetailScreen(
          conversationId: widget.conversationId,
          recipientName: widget.recipientName,
          recipientAvatar: '',
          isDarkMode: true,
          isAutoGenerated: true,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final booking = widget.booking;
    final tracking = _trackingLocation;
    final bookingMap = tracking?['bookings'] as Map<String, dynamic>?;
    final vehicle =
        bookingMap?['vehicles'] as Map<String, dynamic>? ??
        booking['vehicles'] as Map<String, dynamic>?;
    final renter =
        bookingMap?['renter'] as Map<String, dynamic>? ??
        booking['users'] as Map<String, dynamic>?;
    final lat = (tracking?['latitude'] as num?)?.toDouble();
    final lng = (tracking?['longitude'] as num?)?.toDouble();
    final speedMps = (tracking?['speed_mps'] as num?)?.toDouble() ?? 0;
    final speedMph = speedMps * 2.23694;
    final heading = (tracking?['heading_degrees'] as num?)?.toDouble() ?? 0;
    final recordedAt = tracking?['recorded_at']?.toString();
    final destination =
        bookingMap?['dropoff_location']?.toString() ??
        booking['dropoff_location']?.toString() ??
        'Destination unavailable';
    final vehicleName =
        [vehicle?['vehicle_name'], vehicle?['brand'], vehicle?['model']]
            .where((part) => part != null && part.toString().trim().isNotEmpty)
            .join(' ');
    final plateNumber = vehicle?['plate_number']?.toString().trim() ?? '';
    final renterName =
        renter?['full_name']?.toString().trim().isNotEmpty == true
        ? renter!['full_name'].toString().trim()
        : widget.recipientName;
    final trackingStatus = tracking == null
        ? 'Awaiting GPS'
        : speedMph > 4
        ? 'Driving'
        : 'Parked';

    return Scaffold(
      backgroundColor: const Color(0xFF071E2D),
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: Stack(
                children: [
                  Positioned.fill(
                    child: _buildMapBackdrop(
                      lat: lat,
                      lng: lng,
                      destination: destination,
                    ),
                  ),
                  Positioned(
                    top: 12,
                    left: 16,
                    right: 16,
                    child: Row(
                      children: [
                        _buildCircleButton(
                          icon: Icons.arrow_back,
                          onTap: () => Navigator.pop(context),
                        ),
                        const Spacer(),
                        Column(
                          children: const [
                            Text(
                              'LIVE TRACKING',
                              style: TextStyle(
                                color: AppColors.primary,
                                fontSize: 24,
                                fontWeight: FontWeight.w800,
                                letterSpacing: 1.4,
                              ),
                            ),
                            SizedBox(height: 2),
                            Text(
                              'Powered by Mobilis',
                              style: TextStyle(
                                color: AppColors.textSecondary,
                                fontSize: 12,
                              ),
                            ),
                          ],
                        ),
                        const Spacer(),
                        _buildCircleButton(
                          icon: Icons.more_vert,
                          onTap: () => _loadTrackingLocation(showLoader: false),
                        ),
                      ],
                    ),
                  ),
                  Positioned(
                    top: 96,
                    left: 16,
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 14,
                        vertical: 8,
                      ),
                      decoration: BoxDecoration(
                        color: const Color(0xFF6CE5C8).withValues(alpha: 0.85),
                        borderRadius: BorderRadius.circular(999),
                      ),
                      child: Row(
                        children: [
                          const Icon(
                            Icons.circle,
                            size: 10,
                            color: AppColors.success,
                          ),
                          const SizedBox(width: 8),
                          Text(
                            trackingStatus.toUpperCase(),
                            style: const TextStyle(
                              color: Color(0xFF064B3B),
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    right: 16,
                    top: 160,
                    child: Column(
                      children: [
                        _buildCircleButton(
                          icon: Icons.add,
                          onTap: () => setState(() {
                            _zoom = ((_zoom + 1).clamp(6, 18) as num)
                                .toDouble();
                          }),
                        ),
                        const SizedBox(height: 12),
                        _buildCircleButton(
                          icon: Icons.remove,
                          onTap: () => setState(() {
                            _zoom = ((_zoom - 1).clamp(6, 18) as num)
                                .toDouble();
                          }),
                        ),
                        const SizedBox(height: 28),
                        Container(
                          decoration: BoxDecoration(
                            color: AppColors.primary,
                            borderRadius: BorderRadius.circular(999),
                          ),
                          child: IconButton(
                            onPressed: () =>
                                _loadTrackingLocation(showLoader: false),
                            icon: const Icon(
                              Icons.my_location,
                              color: Colors.black,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  Positioned(
                    left: 18,
                    right: 18,
                    bottom: 18,
                    child: _buildBottomSheet(
                      renterName: renterName,
                      vehicleName: vehicleName.isEmpty
                          ? 'Tracked Vehicle'
                          : vehicleName,
                      plateNumber: plateNumber,
                      destination: destination,
                      speedMph: speedMph,
                      heading: _headingLabel(heading),
                      updatedAt: _formatUpdated(recordedAt),
                    ),
                  ),
                  if (_isLoading)
                    const Positioned.fill(
                      child: ColoredBox(
                        color: Color(0x44000000),
                        child: Center(
                          child: CircularProgressIndicator(
                            color: AppColors.primary,
                          ),
                        ),
                      ),
                    ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMapBackdrop({
    required double? lat,
    required double? lng,
    required String destination,
  }) {
    if (lat != null && lng != null) {
      return Stack(
        fit: StackFit.expand,
        children: [
          MobilisLeafletMap(
            key: ValueKey('partner-tracking-$lat-$lng-$_zoom'),
            fallbackLatitude: lat,
            fallbackLongitude: lng,
            initialZoom: _zoom,
            markers: [
              MobilisMapMarker(
                latitude: lat,
                longitude: lng,
                icon: Icons.directions_car_filled_rounded,
                size: 46,
              ),
            ],
          ),
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Color(0x22000000), Color(0xAA071E2D)],
              ),
            ),
          ),
        ],
      );
    }

    return _buildMapFallback(destination);
  }

  Widget _buildMapFallback(String destination) {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFB6E4F3), Color(0xFF6AB5D7), Color(0xFF0F3B57)],
        ),
      ),
      child: Stack(
        children: [
          Positioned.fill(
            child: Opacity(
              opacity: 0.15,
              child: CustomPaint(painter: _GridPainter()),
            ),
          ),
          Align(
            alignment: Alignment.center,
            child: Container(
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.9),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.directions_car_filled,
                color: AppColors.primaryDark,
                size: 34,
              ),
            ),
          ),
          Positioned(
            left: 36,
            right: 36,
            top: 150,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
              decoration: BoxDecoration(
                color: AppColors.primary,
                borderRadius: BorderRadius.circular(999),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(
                    Icons.location_on_outlined,
                    color: Colors.black,
                    size: 16,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      destination,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        color: Colors.black,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomSheet({
    required String renterName,
    required String vehicleName,
    required String plateNumber,
    required String destination,
    required double speedMph,
    required String heading,
    required String updatedAt,
  }) {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 14, 20, 20),
      decoration: const BoxDecoration(
        color: Color(0xFF082A4C),
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 52,
            height: 5,
            decoration: BoxDecoration(
              color: Colors.white24,
              borderRadius: BorderRadius.circular(999),
            ),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Container(
                width: 56,
                height: 56,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  border: Border.all(color: AppColors.primary, width: 2),
                  color: const Color(0xFF15395A),
                ),
                child: const Icon(
                  Icons.person,
                  color: AppColors.textPrimary,
                  size: 28,
                ),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Current Renter',
                      style: TextStyle(
                        color: AppColors.textSecondary,
                        fontSize: 13,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      renterName,
                      style: const TextStyle(
                        color: AppColors.textPrimary,
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 4),
                    const Row(
                      children: [
                        Icon(Icons.star, color: AppColors.primary, size: 14),
                        SizedBox(width: 4),
                        Text(
                          '4.9 PRO',
                          style: TextStyle(
                            color: AppColors.primary,
                            fontSize: 12,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  const Text(
                    'Vehicle',
                    style: TextStyle(
                      color: AppColors.textSecondary,
                      fontSize: 13,
                    ),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    vehicleName,
                    textAlign: TextAlign.right,
                    style: const TextStyle(
                      color: AppColors.textPrimary,
                      fontSize: 17,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  if (plateNumber.isNotEmpty) ...[
                    const SizedBox(height: 2),
                    Text(
                      plateNumber,
                      style: const TextStyle(
                        color: AppColors.textSecondary,
                        fontSize: 12,
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
          const SizedBox(height: 18),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 16),
            decoration: BoxDecoration(
              color: const Color(0xFF0E355A),
              borderRadius: BorderRadius.circular(22),
              border: Border.all(color: Colors.white10),
            ),
            child: Row(
              children: [
                Expanded(
                  child: _buildMetric(
                    label: 'SPEED',
                    value: '${speedMph.toStringAsFixed(0)} mph',
                  ),
                ),
                Expanded(
                  child: _buildMetric(label: 'HEADING', value: heading),
                ),
                Expanded(
                  child: _buildMetric(label: 'UPDATED', value: updatedAt),
                ),
              ],
            ),
          ),
          const SizedBox(height: 18),
          Row(
            children: [
              Expanded(
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 42,
                      height: 42,
                      decoration: BoxDecoration(
                        color: AppColors.primary.withValues(alpha: 0.15),
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(
                        Icons.location_on_outlined,
                        color: AppColors.primary,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Destination',
                            style: TextStyle(
                              color: AppColors.textSecondary,
                              fontSize: 13,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            destination,
                            style: const TextStyle(
                              color: AppColors.textPrimary,
                              fontSize: 16,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  const Text(
                    'Location',
                    style: TextStyle(
                      color: AppColors.textSecondary,
                      fontSize: 13,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    _trackingLocation == null ? 'Unavailable' : 'Live',
                    style: const TextStyle(
                      color: AppColors.textPrimary,
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 22),
          Row(
            children: [
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: widget.conversationId.trim().isEmpty
                      ? null
                      : _openConversation,
                  icon: const Icon(Icons.chat_bubble_outline, size: 20),
                  label: const Text('Message Renter'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.black,
                    minimumSize: const Size.fromHeight(52),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                    textStyle: const TextStyle(
                      fontSize: 17,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 14),
              Container(
                width: 64,
                height: 64,
                decoration: BoxDecoration(
                  color: const Color(0xFF2A2248),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: const Color(0x55FF4F8B)),
                ),
                child: const Icon(
                  Icons.podcasts_rounded,
                  color: Color(0xFFFF4F8B),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildMetric({required String label, required String value}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: AppColors.textSecondary,
            fontSize: 11,
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 6),
        Text(
          value,
          style: const TextStyle(
            color: AppColors.textPrimary,
            fontSize: 17,
            fontWeight: FontWeight.w700,
          ),
        ),
      ],
    );
  }

  Widget _buildCircleButton({
    required IconData icon,
    required VoidCallback onTap,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xCC0A2D4A),
        borderRadius: BorderRadius.circular(22),
      ),
      child: IconButton(
        onPressed: onTap,
        icon: Icon(icon, color: Colors.white),
      ),
    );
  }

  String _headingLabel(double headingDegrees) {
    if (headingDegrees.isNaN) return 'Unknown';
    const directions = [
      'North',
      'NE',
      'East',
      'SE',
      'South',
      'SW',
      'West',
      'NW',
    ];
    final index = (((headingDegrees % 360) / 45).round()) % directions.length;
    return directions[index];
  }

  String _formatUpdated(String? timestamp) {
    if (timestamp == null || timestamp.isEmpty) return 'N/A';
    final parsed = DateTime.tryParse(timestamp)?.toLocal();
    if (parsed == null) return 'N/A';
    final hour = parsed.hour % 12 == 0 ? 12 : parsed.hour % 12;
    final minute = parsed.minute.toString().padLeft(2, '0');
    final suffix = parsed.hour >= 12 ? 'PM' : 'AM';
    return '$hour:$minute $suffix';
  }
}

class _GridPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.white24
      ..strokeWidth = 1;

    const spacing = 42.0;
    for (double x = 0; x < size.width; x += spacing) {
      canvas.drawLine(Offset(x, 0), Offset(x, size.height), paint);
    }
    for (double y = 0; y < size.height; y += spacing) {
      canvas.drawLine(Offset(0, y), Offset(size.width, y), paint);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
