/// Luzon service-area data for cascading pickup/drop-off dropdowns.
///
/// Visayas and Mindanao are intentionally excluded for now.
class PhilippineLocations {
  static final Map<String, List<String>> provinces = {
    'Metro Manila': [
      'Caloocan',
      'Las Pinas',
      'Makati',
      'Malabon',
      'Mandaluyong',
      'Manila',
      'Marikina',
      'Muntinlupa',
      'Navotas',
      'Paranaque',
      'Pasay',
      'Pasig',
      'Pateros',
      'Quezon City',
      'San Juan',
      'Taguig',
      'Valenzuela',
    ],
    'Ilocos Norte': [
      'Laoag',
      'Batac',
      'Paoay',
      'Pasuquin',
      'Bacarra',
      'Dingras',
    ],
    'Ilocos Sur': [
      'Vigan',
      'Candon',
      'Narvacan',
      'Santa Maria',
      'Tagudin',
      'Sinait',
    ],
    'La Union': [
      'San Fernando',
      'Agoo',
      'Bauang',
      'Naguilian',
      'Rosario',
      'Bacnotan',
    ],
    'Pangasinan': [
      'Alaminos',
      'Anda',
      'Bayambang',
      'Binalonan',
      'Bolinao',
      'Calasiao',
      'Dagupan',
      'Lingayen',
      'Malasiqui',
      'Manaoag',
      'Mangaldan',
      'Pozorrubio',
      'Rosales',
      'San Carlos',
      'Sual',
      'Urdaneta',
    ],
    'Batanes': ['Basco', 'Itbayat', 'Ivana', 'Mahatao', 'Sabtang', 'Uyugan'],
    'Cagayan': [
      'Tuguegarao',
      'Aparri',
      'Lal-lo',
      'Sanchez-Mira',
      'Solana',
      'Tuao',
    ],
    'Isabela': ['Ilagan', 'Cauayan', 'Santiago', 'Roxas', 'Echague', 'Alicia'],
    'Nueva Vizcaya': [
      'Bayombong',
      'Solano',
      'Bambang',
      'Aritao',
      'Dupax del Norte',
      'Kasibu',
    ],
    'Quirino': [
      'Cabarroguis',
      'Diffun',
      'Maddela',
      'Nagtipunan',
      'Aglipay',
      'Saguday',
    ],
    'Abra': ['Bangued', 'Boliney', 'Bucay', 'Dolores', 'Lagangilang', 'Tayum'],
    'Apayao': ['Kabugao', 'Calanasan', 'Conner', 'Flora', 'Luna', 'Pudtol'],
    'Benguet': [
      'Baguio',
      'La Trinidad',
      'Itogon',
      'Tuba',
      'Mankayan',
      'Buguias',
    ],
    'Ifugao': ['Lagawe', 'Banaue', 'Kiangan', 'Lamut', 'Mayoyao', 'Hingyon'],
    'Kalinga': ['Tabuk', 'Lubuagan', 'Pasil', 'Pinukpuk', 'Rizal', 'Tinglayan'],
    'Mountain Province': [
      'Bontoc',
      'Sagada',
      'Bauko',
      'Besao',
      'Natonin',
      'Paracelis',
    ],
    'Aurora': [
      'Baler',
      'Dingalan',
      'Dipaculao',
      'Maria Aurora',
      'San Luis',
      'Casiguran',
    ],
    'Bataan': [
      'Balanga',
      'Mariveles',
      'Dinalupihan',
      'Orion',
      'Orani',
      'Pilar',
    ],
    'Bulacan': [
      'Malolos',
      'Meycauayan',
      'San Jose del Monte',
      'Baliuag',
      'Marilao',
      'Santa Maria',
    ],
    'Nueva Ecija': [
      'Cabanatuan',
      'Palayan',
      'Gapan',
      'San Jose',
      'Science City of Munoz',
      'Talavera',
    ],
    'Pampanga': [
      'San Fernando',
      'Angeles',
      'Mabalacat',
      'Mexico',
      'Guagua',
      'Porac',
    ],
    'Tarlac': [
      'Tarlac City',
      'Capas',
      'Concepcion',
      'Paniqui',
      'Bamban',
      'Gerona',
    ],
    'Zambales': [
      'Olongapo',
      'Iba',
      'Subic',
      'Castillejos',
      'San Antonio',
      'Botolan',
    ],
    'Batangas': [
      'Batangas City',
      'Lipa',
      'Tanauan',
      'Nasugbu',
      'Lemery',
      'Santo Tomas',
    ],
    'Cavite': [
      'Bacoor',
      'Cavite City',
      'Dasmarinas',
      'General Trias',
      'Imus',
      'Tagaytay',
      'Trece Martires',
    ],
    'Laguna': [
      'Calamba',
      'San Pablo',
      'Santa Rosa',
      'Binan',
      'Cabuyao',
      'Los Banos',
    ],
    'Quezon': [
      'Lucena',
      'Tayabas',
      'Candelaria',
      'Sariaya',
      'Pagbilao',
      'Atimonan',
    ],
    'Rizal': ['Antipolo', 'Cainta', 'Taytay', 'Angono', 'Binangonan', 'Tanay'],
    'Marinduque': [
      'Boac',
      'Buenavista',
      'Gasan',
      'Mogpog',
      'Santa Cruz',
      'Torrijos',
    ],
    'Occidental Mindoro': [
      'Mamburao',
      'San Jose',
      'Sablayan',
      'Calintaan',
      'Rizal',
      'Santa Cruz',
    ],
    'Oriental Mindoro': [
      'Calapan',
      'Pinamalayan',
      'Roxas',
      'Bongabong',
      'Naujan',
      'Puerto Galera',
    ],
    'Palawan': [
      'Puerto Princesa',
      'Coron',
      'El Nido',
      'Roxas',
      'Brooke\'s Point',
      'Narra',
    ],
    'Romblon': [
      'Romblon',
      'Odiongan',
      'San Agustin',
      'San Fernando',
      'Cajidiocan',
      'Looc',
    ],
    'Albay': ['Legazpi', 'Ligao', 'Tabaco', 'Daraga', 'Guinobatan', 'Polangui'],
    'Camarines Norte': [
      'Daet',
      'Basud',
      'Labo',
      'Mercedes',
      'Paracale',
      'Talisay',
    ],
    'Camarines Sur': ['Naga', 'Iriga', 'Pili', 'Baao', 'Calabanga', 'Caramoan'],
    'Catanduanes': [
      'Virac',
      'Bato',
      'Caramoran',
      'Pandan',
      'San Andres',
      'Viga',
    ],
    'Masbate': [
      'Masbate City',
      'Aroroy',
      'Cataingan',
      'Mandaon',
      'Milagros',
      'Uson',
    ],
    'Sorsogon': [
      'Sorsogon City',
      'Bulan',
      'Donsol',
      'Gubat',
      'Irosin',
      'Matnog',
    ],
  };

  static final Map<String, List<String>> barangays = {
    'Caloocan': [
      'Bagong Barrio',
      'Bagumbong',
      'Camarin',
      'Deparo',
      'Grace Park',
    ],
    'Las Pinas': ['Almanza Uno', 'Almanza Dos', 'Pilar', 'Talon Uno', 'Zapote'],
    'Makati': ['Ayala', 'Bel-Air', 'Poblacion', 'San Lorenzo', 'Urdaneta'],
    'Malabon': ['Acacia', 'Catmon', 'Concepcion', 'Longos', 'Tonsuya'],
    'Mandaluyong': [
      'Addition Hills',
      'Barangka Drive',
      'Highway Hills',
      'Plainview',
      'Wack-Wack',
    ],
    'Manila': ['Binondo', 'Ermita', 'Malate', 'Quiapo', 'Sampaloc'],
    'Marikina': [
      'Concepcion Uno',
      'Fortune',
      'Marikina Heights',
      'San Roque',
      'Sto. Nino',
    ],
    'Muntinlupa': ['Alabang', 'Ayala Alabang', 'Poblacion', 'Putatan', 'Sucat'],
    'Navotas': [
      'Bagumbayan North',
      'Daanghari',
      'North Bay Boulevard South',
      'San Jose',
      'Tangos',
    ],
    'Paranaque': ['BF Homes', 'Don Bosco', 'Moonwalk', 'San Antonio', 'Tambo'],
    'Pasay': [
      'Barangay 76',
      'Barangay 183',
      'Malibay',
      'Maricaban',
      'San Rafael',
    ],
    'Pasig': [
      'Bagong Ilog',
      'Kapitolyo',
      'Ortigas Center',
      'San Antonio',
      'Ugong',
    ],
    'Pateros': ['Aguho', 'Magtanggol', 'Poblacion', 'San Pedro', 'Santa Ana'],
    'Quezon City': [
      'Batasan Hills',
      'Commonwealth',
      'Cubao',
      'Diliman',
      'Fairview',
    ],
    'San Juan': [
      'Addition Hills',
      'Balong-Bato',
      'Greenhills',
      'Progreso',
      'West Crame',
    ],
    'Taguig': ['Bagumbayan', 'BGC', 'Central Bicutan', 'Pinagsama', 'Ususan'],
    'Valenzuela': [
      'Karuhatan',
      'Malinta',
      'Marulas',
      'Paso de Blas',
      'Wawang Pulo',
    ],
    'Alaminos': [
      'Balangobong',
      'Baleyadaan',
      'Bisocol',
      'Lucap',
      'Magsaysay',
      'Poblacion',
      'San Jose',
      'Telbang',
      'Victoria',
    ],
    'Anda': [
      'Awile',
      'Awag',
      'Batiarao',
      'Cabungan',
      'Carot',
      'Imbo',
      'Poblacion',
      'Roxas',
      'Tondol',
    ],
    'Bayambang': [
      'Amancosiling Norte',
      'Amancosiling Sur',
      'Bical Norte',
      'Bical Sur',
      'Bued',
      'Hermosa',
      'Poblacion Sur',
      'San Gabriel',
      'Wawa',
    ],
    'Binalonan': [
      'Balangobong',
      'Bugayong',
      'Camangaan',
      'Canarvacanan',
      'Linmansangan',
      'Poblacion',
      'San Felipe Central',
      'San Pablo',
      'Sumabnit',
    ],
    'Bolinao': [
      'Arnedo',
      'Balingasay',
      'Binabalian',
      'Concordia',
      'Germinal',
      'Ilog-Malino',
      'Patar',
      'Poblacion',
      'Victory',
    ],
    'Calasiao': [
      'Ambonao',
      'Banaoang',
      'Buenlag',
      'Dinalaoan',
      'Gabaldon',
      'Lasip',
      'Longos',
      'Poblacion East',
      'Talibaew',
    ],
    'Dagupan': [
      'Bacayao Norte',
      'Bacayao Sur',
      'Bonuan Binloc',
      'Bonuan Boquig',
      'Bonuan Gueset',
      'Calmay',
      'Caranglaan',
      'Lucao',
      'Malued',
      'Pantal',
      'Poblacion Oeste',
      'Tapuac',
    ],
    'Lingayen': [
      'Aliwekwek',
      'Baay',
      'Balangobong',
      'Domalandan Center',
      'Estanza',
      'Libsong East',
      'Libsong West',
      'Poblacion',
      'Wawa',
    ],
    'Malasiqui': [
      'Abonagan',
      'Aliaga',
      'Banaoang',
      'Bongar',
      'Calbueg',
      'Canan Norte',
      'Canan Sur',
      'Lareg-lareg',
      'Poblacion',
    ],
    'Manaoag': [
      'Babasit',
      'Baritao',
      'Bucao',
      'Cabanbanan',
      'Calaocan',
      'Inamotan',
      'Poblacion',
      'San Ramon',
      'Tebuel',
    ],
    'Mangaldan': [
      'Amansabina',
      'Banaoang',
      'Bantayan',
      'Buenlag',
      'David',
      'Guesang',
      'Poblacion',
      'Salay',
      'Tebag',
    ],
    'Pozorrubio': [
      'Alipangpang',
      'Bobonan',
      'Don Benito',
      'Inoman',
      'Malasin',
      'Nangalisan',
      'Poblacion',
      'Talogtog',
      'Villegas',
    ],
    'Rosales': [
      'Acop',
      'Bakit-bakit',
      'Carmen East',
      'Carmen West',
      'Don Antonio Village',
      'Poblacion',
      'San Bartolome',
      'Tomana East',
      'Tomana West',
    ],
    'San Carlos': [
      'Abanon',
      'Agdao',
      'Ano',
      'Balite Sur',
      'Bocboc',
      'Bolingit',
      'Bonifacio',
      'Cobol',
      'Guelew',
      'Lucban',
      'Mabini',
      'Palaris',
      'Poblacion',
      'San Juan',
      'San Pedro',
      'Tebag',
      'Turac',
    ],
    'Sual': [
      'Baquioen',
      'Baybay Norte',
      'Baybay Sur',
      'Caoayan',
      'Macaycayawan',
      'Poblacion',
      'Sioasio East',
      'Sioasio West',
      'Victoria',
    ],
    'Urdaneta': [
      'Anonas',
      'Bactad East',
      'Bayaoas',
      'Camantiles',
      'Catablan',
      'Nancayasan',
      'Poblacion',
      'San Vicente',
      'Santa Lucia',
    ],
    'Default': [
      'Poblacion',
      'Centro',
      'Barangay 1',
      'Barangay 2',
      'Barangay 3',
      'Other',
    ],
  };

  static const String psdc_garage = 'PSDC Garage, Manila';

  static List<String> getCitiesForProvince(String province) {
    return provinces[province] ?? [];
  }

  static List<String> getBarangaysForCity(String city) {
    return barangays[city] ?? barangays['Default']!;
  }

  static List<String> getAllProvinces() => provinces.keys.toList();

  static String formatLocation(String barangay, String city, String province) {
    return '$barangay, $city, $province';
  }
}
