self.MOBILIS_FIREBASE_CONFIG = {
  apiKey: 'YOUR_FIREBASE_WEB_API_KEY',
  authDomain: 'YOUR_PROJECT.firebaseapp.com',
  projectId: 'YOUR_FIREBASE_WEB_PROJECT_ID',
  storageBucket: 'YOUR_PROJECT.firebasestorage.app',
  messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
  appId: 'YOUR_FIREBASE_WEB_APP_ID',
  measurementId: 'YOUR_FIREBASE_MEASUREMENT_ID',
};

self.MOBILIS_FIREBASE_VAPID_KEY = 'YOUR_FIREBASE_WEB_VAPID_KEY';
